version: '3'
services:
    #1. Главный Проект
    basic-node:
        container_name: web-node
        build: 
            context: .
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - '80:3000'
        networks:
            - basic_network
        links:
            - db
        environment:
            DB_HOST: db-basic
        volumes:
            - ./app:/var/www/appNode
    #2. База данных
    db:
        image: mysql:5.7
        restart: unless-stopped
        container_name: db-basic
        networks:
            - basic_network
        environment:
            MYSQL_ROOT_PASSWORD: kek
            MYSQL_PASSWORD: kek
            MYSQL_USER: saint
        volumes:
            - './db:/var/lib/mysql'

    # 3. Веб интерфейс Базы данных
    phpmyadmin:
        depends_on:
            - db
        image: 'phpmyadmin:5.0-fpm-alpine'
        container_name: pma
        restart: always
        ports:
            - '5050:80'
        environment:
            UPLOAD_LIMIT: 300M
        networks:
            - basic_network
           
 # Внутреняя сеть контейнеров   
networks:
    basic_network:
        external: true
